- hosts: http-auth
  tasks:
    -package:
        name: "httpd"
        state: present

    -copy:
        dest: "/var/www/html/index.html"
        content: "this is session 8 htttpd authorization"

    -replace:
        path: "/etc/httpd/conf/httpd.conf"
        regexp: "AllowOverride None"
        replaace: "AllowOverride AuthConfig"

    -copy:
        dest: "/var/www/html/.htaccess"
        src: ".htaccess"

    -package:
        name: "python36"
        state: present

    -pip:
        name: "passlib"

    -htpasswd:
        path: "/etc/www.htpasswd"
        name: "sid"
        password: "ran@1234"

    -service:
        name: "httpd"
        state: restarted
        

